//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZigZag.Editor.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Shaders {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Shaders() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ZigZag.Editor.Resources.Shaders", typeof(Shaders).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #version 330
        ///
        ///out vec4 outputColor;
        ///
        ///void main()
        ///{
        ///    outputColor = vec4(1.0, 1.0, 0.0, 1.0);
        ///}
        ///.
        /// </summary>
        internal static string ImguiFragShaderSource {
            get {
                return ResourceManager.GetString("ImguiFragShaderSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // For more information on how shaders work, check out the web version of this tutorial
        ///// I&apos;ll include a simpler summary here.
        ///
        ///// First non-comment line should always be a #version statement; this just tells the GLSL compiler what version it should use
        ///#version 330 core
        ///
        ///// GLSL&apos;s syntax is somewhat like C, but it has a few differences.
        ///
        ///// There are four different types of variables in GLSL: input, output, uniform, and internal.
        ///// Input variables are sent from the buffer, in a way defined by GL.VertexAt [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ImguiVertShaderSource {
            get {
                return ResourceManager.GetString("ImguiVertShaderSource", resourceCulture);
            }
        }
    }
}
